name: Echo ROLE - Shared

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: {} # optional if you're not passing secrets

jobs:
  echo-role:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Echo the ROLE
        run: echo "ROLE is $ROLE"
        env:
          ROLE: ${{ vars.ROLE }}
